## dsp
sample_rate : 24000
window_length: 50.0 # ms
hop_length: 12.5 # ms
mel_min: 1.0e-5 ## need .0 to make it a float
mel_dim: 80
n_fft: 2048

## wavegru
rnn_dim: 1024
frames_per_sequence: 67
num_pad_frames: 62
upsample_factors: [5, 3, 20]

## training
batch_size : 256
lr: 1024.0e-6
model_prefix: "wavegru_vocoder_1024"
tf_data_dir : "./tf_data"
ckpt_dir : "./ckpts"
