sample_rate : 22050
window_length: 50.0 # ms
hop_length: 12.5 # ms
frames_per_sequence: 44
num_pad_frames: 40
mel_min: 1.0e-5 ## need .0 to make it a float
mel_dim: 80
n_fft: 2048
tf_data_dir : "./tf_data"

## training
batch_size : 32
lr: 1024.0e-6
model_prefix: "wavegru_512"